project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!archived/"

website:
  title: "Emory NRSG 736: Quantitative Analysis of Clinical Research Data"
  description: "Emory NRSG 736: Quantitative Analysis of Clinical Research Data"
  
  sidebar:
    search: true
    logo: HexStickers_N736_crop.png
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



